const permissions = {
  grantPermissionRole: "Role:GrantPermission",
  createHub: "Hub:Create",
  updateHub: "Hub:Update",
  updateStateHub: "Hub:UpdateState",
  createUser: "User:Create",
  readUser: "User:Read",
  updateStateUser: "User:Update",
  updateUser: "User:Update",
  createRole: "Role:Create",
  readRole: "Role:Read",
  updateRole: "Role:Update",
  deleteRole: "Role:Delete",
  updateNotification: "Notification:Update",
  grantRoleUser: "User:GrantRole",
  configSystem: "System:Config",
  updateCheckIn: "CheckIn:Update",
  updateQuizz: "Quizz:Update",
  updateSchedule: "Schedule:Update",
  deletePostGroup: "Group:DeletePost",
  pinPostGroup: "Group:PinPost",
  reactPostGroup: "Group:ReactPost",
  approvePostGroup: "Post:Approve",
  viewPostGroup: "Group:ViewPost",
  deleteDocument: "Document:Delete",
  createGroup: "Group:Create",
  updateGroup: "Group:Update",
  updateMembersGroup: "Group:UpdateMembers",
};
export default permissions